### PR TITLE
Fix/matmul

### PR DESCRIPTION
**Pull request by msurkovsky**
Fix of matrix multiplication example (point-to-point version). There were two problems: firstly, the initial distribution of sub-matrices and their final composition were wrong. Now, it's implemented the distribution described in systolic algorithm from book by Foster (in fact a variation of Cannon's algorithm). Secondly, the preparation (distribution of sub-matrices) must not be mixed with the computation. Once the sub-matrices are correctly distributed among processes the computation will be OK, if they are mixed then wrong sub-matrices are multiplied which leads to wrong results. In order to solve this problem a new sync place was added to the example representing the condition that computation may not start util the initial distribution is done. Actually I'd be glad if you (can) come up with a better (nicer) solution. IMHO this is too complicated construct to represent such a condition.

Moreover, the matmul-cc example suffer by the same problem (preparation & computation may be mixed). This is caused by the barrier, because it synchronizes only until all processes reach the same place, however the send is not confirmed, hence the data may be received after first compute => the same mistake. Verification doesn't reveal such a mistake because it implements "synchronized" barrier.

### CODE REVIEW

**Comment by spirali** [comment]
If you replace "distribute" transition by barrier (as we have discussed) then I merge it. Thank you

**Comment by msurkovsky** [comment]
Ok, but which version do you mean, the correct one or "semantically" correct? :)

**Comment by spirali** [comment]
For the correct semantics, we are going fix the problem, so it would be nice to have nice examples after the fix:)

**Comment by msurkovsky** [comment]
Ok I amended the last commit with a final fix.

**Pull request merged**
